# Generated by Django 6.0.5 on 2026-06-13 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('tourist', 'Tourist'), ('student', 'Student'), ('work', 'Work'), ('business', 'Business'), ('transit', 'Transit'), ('family', 'Family/Spousal')], max_length=50)),
                ('processing_time', models.CharField(blank=True, max_length=100)),
                ('fee_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('validity', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_types', to='visas.country')),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon_category', models.CharField(choices=[('passport', 'Passport'), ('photo', 'Photograph'), ('financial', 'Financial Document'), ('employment', 'Employment Document'), ('accommodation', 'Accommodation Proof'), ('travel', 'Travel History'), ('medical', 'Medical Document'), ('educational', 'Educational Certificate'), ('other', 'Other')], default='other', max_length=50)),
                ('importance', models.CharField(choices=[('mandatory', 'Mandatory'), ('optional', 'Optional'), ('conditional', 'Conditional')], default='mandatory', max_length=20)),
                ('condition_note', models.CharField(blank=True, max_length=255)),
                ('sample_description', models.TextField(blank=True)),
                ('official_source_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('last_verified', models.DateField(blank=True, null=True)),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='visas.visatype')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
