# Generated by Django 6.0.5 on 2026-06-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequirement',
            name='common_mistakes',
            field=models.TextField(blank=True, help_text='Frequent errors leading to rejection.'),
        ),
        migrations.AddField(
            model_name='visatype',
            name='tips',
            field=models.TextField(blank=True, help_text='General tips, e.g., fees in Naira, booking advice.'),
        ),
    ]
